---
- name: Check HDFS
  hosts: namenode
  sudo: true
  sudo_user: hadoop
  vars_files:
    - local.yml
  tasks:
    - name: Run 'hadoop fs -ls /'
      command: ./bin/hadoop fs -ls /
               chdir=/home/hadoop/{{hadoop_unzip_dir}}
    - name: Run 'hadoop TestDFSIO -write'
      command: ./bin/hadoop jar hadoop-test-{{hadoop_version}}.jar TestDFSIO -write -nrFiles 2 -fileSize 2
               chdir=/home/hadoop/{{hadoop_unzip_dir}}
