---
- name: Deletes datanodes directories
  hosts: slaves
  sudo: true
  vars_files:
    - general.yml
    - local.yml
  tasks:
    - name: Delete /srv/hadoop
      file: path=/srv/hadoop state=absent
      tags: rm-rf
    - name: Next step
      debug: msg="Now you should run 'ansible-playbook -i hosts -v site.yml -t hadoop'"
