---
- name: Shutdown node servers
  hosts: nodes
  sudo: true
  gather_facts: no
  vars_files:
    - general.yml
    - local.yml
  tasks:
    - command: halt

- name: Shutdown infrastructure servers (only once nodes are down)
  hosts: infrastructure
  sudo: true
  gather_facts: no
  vars_files:
    - general.yml
    - local.yml
  tasks:
    - command: halt

