---
- name: Hadoop nodes setup
  hosts: nodes
  sudo: true
  vars_files:
    - local.yml
  roles:
    - server

- name: Setup Hadoop namenode
  hosts: namenode
  sudo: true
  sudo_user: hadoop
  vars_files:
    - local.yml
  roles:
    - namenode
