---

- name: Hadoop master node setup
  hosts: master
  sudo: true
  vars_files:
    - local.yml
  roles:
    - server
    - master

- name: Hadoop slave nodes setup
  hosts: slave
  sudo: true
  vars_files:
    - local.yml
  roles:
    - server
    - slave
