---

- name: Hadoop master node setup
  hosts: master
  user: horacio
  sudo: true

  roles:
    - server
    - master

- name: Hadoop slave nodes setup
  hosts: slave
  user: horacio
  sudo: true

  roles:
    - server
    - slave
