---
- name: Hadoop nodes setup
  hosts: nodes
  sudo: true
  vars_files:
    - local.yml
    - general.yml
  roles:
    - server
    - java
    - hadoop

- name: Setup Hadoop namenode
  hosts: namenode
  sudo: true
  vars_files:
    - local.yml
    - general.yml
  roles:
    - server
    - java
    - namenode
