---

- name: Stop Hadoop cluster
  hosts: master
  sudo: true
  sudo_user: hadoop
  gather_facts: no
  vars_files:
    - local.yml
  tasks:
    - command: /home/hadoop/{{ hadoop_unzip_dir }}/bin/stop-all.sh
