---
- name: Wipe datanodes
  hosts: slaves
  sudo: true
  vars_files:
    - local.yml
  tasks:
    - name: Fill disks with zeros
      command: dd if=/dev/zero of=/srv/hadoop/data/ZEROS bs=512k
      ignore_errors: True
    - name: Remove file with zeros
      file: path=/srv/hadoop/data/ZEROS state=absent
    - name: Wipe data
      command: wipe -f -F -q -Q 1 -r -S p -s -Z /srv/hadoop/data
      tags: wipe
    - name: Delete /srv/hadoop
      file: path=/srv/hadoop state=absent
      tags: rm-rf
