---
- name: Install basic packages
  yum: name={{ item }} state=installed
  with_items:
    - httpd
    - php
  notify:
    - restart httpd
  tags: yum

- name: Create NFS directory
  file: path=/srv/nfs owner=hadoop group=hadoop mode=0775 state=directory
  tags: nfs

- name: Setup NFS server
  template: src=exports dest=/etc/exports
  notify:
    - reload nfs exports
  tags: nfs

- name: Setup services
  service: name={{ item }} enabled=yes state=started
  with_items:
    - rpcbind
    - nfslock
    - nfs
    - httpd
  tags: nfs

- name: Upload KickStart files to web server
  template: src=kickstart--{{ansible_distribution}}-{{ansible_distribution_version}}.cfg.php dest=/var/www/html/kickstart.cfg.php owner=root group=root mode=0644
  tags: kickstart

- name: Upload initial authorized_keys to web server
  template: src=files/kickstart_authorized_keys dest=/var/www/html/kickstart_authorized_keys owner=root group=root mode=0644
  tags: kickstart


