---
- name: YUM - disable fastestmirror plugin
  ini_file: dest=/etc/yum/pluginconf.d/fastestmirror.conf section=main option=enabled value=0
  tags: yum

- name: YUM - Setup proxy
  ini_file: dest=/etc/yum.conf section=main option=proxy value=http://proxy.fx8120.hgdeoro.com.ar:3128
  tags: yum

- name: Use specific YUM mirror
  template: src={{ansible_distribution}}-{{ansible_distribution_version}}--CentOS-Base.repo dest=/etc/yum.repos.d/CentOS-Base.repo
  tags: yum

- name: Install basic packages
  yum: name={{ item }} state=installed
  with_items:
     - vim-enhanced
     - openssh-clients
     - cifs-utils
     - git
     - nfs-utils
     - portmap
#     - tcpdump
#     - nmap
#     - screen
  tags: yum

- name: Setup proxy via env variables
  template: src=etc--profile.d--proxy.sh dest=/etc/profile.d/proxy.sh

- name: Setup proxy on wgetrc
  lineinfile: dest=/etc/wgetrc regexp="^http_proxy"  line="http_proxy = http://proxy.fx8120.hgdeoro.com.ar:3128"

- name: Setup proxy on wgetrc
  lineinfile: dest=/etc/wgetrc regexp="^https_proxy" line="https_proxy = http://proxy.fx8120.hgdeoro.com.ar:3128"

- name: Setup proxy on wgetrc
  lineinfile: dest=/etc/wgetrc regexp="^ftp_proxy" line="ftp_proxy = http://proxy.fx8120.hgdeoro.com.ar:3128"

- name: Setup proxy on wgetrc
  lineinfile: dest=/etc/wgetrc regexp="^use_proxy"   line="use_proxy = on"
  
