---
- name: Check CentOS version
  fail: msg="Only {{ansible_distribution}} {{ansible_distribution_version}} supported"
  when: ansible_distribution != 'CentOS' or ansible_distribution_version != '6.4'
  tags: check

- name: YUM - disable fastestmirror plugin
  ini_file: dest=/etc/yum/pluginconf.d/fastestmirror.conf section=main option=enabled value=0
  tags: yum

- name: YUM - Setup proxy
  ini_file: dest=/etc/yum.conf section=main option=proxy value={{proxy}}
  tags: yum

- name: Use specific YUM mirror
  template: src={{ansible_distribution}}-{{ansible_distribution_version}}--CentOS-Base.repo dest=/etc/yum.repos.d/CentOS-Base.repo
  tags: yum

- name: Copy installers
  copy: src=files/{{item}} dest=/tmp/{{item}} owner=root group=root mode=0644 force=no
  with_items:
    - "{{ hadoop_tgz }}"
  tags: upload

- name: Register EPEL repository
  yum: name="https://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm" state=present
  tags: yum

- name: Register Cloudera repository
  yum: name="http://archive.cloudera.com/cdh4/one-click-install/redhat/6/x86_64/cloudera-cdh-4-0.x86_64.rpm" state=present
  tags: yum

- name: Install basic packages
  yum: name={{ item }} state=installed
  with_items:
     - vim-enhanced
     - openssh-clients
     - cifs-utils
     - git
     - nfs-utils
     - portmap
     - wipe
     - lzo
     - lzo-devel
  tags: yum

#- name: Install packages of Base group
#  yum: name=@base state=installed
#  # FIXME: this shouldn't be run every time since this is time consuming
#  # sudo yum groupinstall base
#  when: "{{ lookup('env','INSTALL_BASE_GROUP') }} == '1'"
#  tags: yum

- name: Install snappy
  yum: name=http://pkgs.repoforge.org/snappy/snappy-1.0.5-1.el6.rf.x86_64.rpm state=installed
  tags: yum

- name: Setup proxy via env variables
  template: src=etc--profile.d--proxy.sh dest=/etc/profile.d/proxy.sh
  tags: proxy

- name: Setup proxy on wgetrc
  lineinfile: dest=/etc/wgetrc regexp="^{{item.re}}"  line="{{item.line}}"
  with_items:
     - { re: 'http_proxy',  line: 'http_proxy = {{ proxy }}' }
     - { re: 'https_proxy', line: 'https_proxy = {{ proxy }}' }
     - { re: 'ftp_proxy',   line: 'ftp_proxy = {{ proxy }}' }
     - { re: 'use_proxy',   line: 'use_proxy = on' }
  tags: proxy

- name: Create Hadoop group
  group: name=hadoop gid=599 state=present

- name: Create Hadoop user
  user: name=hadoop comment="User for Hadoop services" uid=599 group=hadoop state=present

- name: Setup ssh authorized_key
  # FIXME: remove 'horacio' and replace for 'ks_username', or better: 'custom_username'
  authorized_key: user="{{item}}" key="{{lookup('file', 'local/authorized_key.txt' )}}"
  with_items:
     - root
     - horacio
     - hadoop
  tags: ssh

- name: Setup ssh keys
  # FIXME: remove 'horacio' and replace for 'ks_username', or better: 'custom_username'
  copy: src=local/{{item.f}} dest={{item.h}}/.ssh/{{item.f}} owner={{item.u}} group={{item.u}} mode=0600
  with_items:
    - { u: 'root',    h: '/root',         f: 'id_rsa' }
    - { u: 'root',    h: '/root',         f: 'id_rsa.pub' }
    - { u: 'hadoop',  h: '/home/hadoop',  f: 'id_rsa' }
    - { u: 'hadoop',  h: '/home/hadoop',  f: 'id_rsa.pub' }
    - { u: 'horacio', h: '/home/horacio', f: 'id_rsa' }
    - { u: 'horacio', h: '/home/horacio', f: 'id_rsa.pub' }
  tags: ssh
