---
- name: YUM - disable fastestmirror plugin
  ini_file: dest=/etc/yum/pluginconf.d/fastestmirror.conf section=main option=enabled value=0
  tags: yum

- name: YUM - Setup proxy
  ini_file: dest=/etc/yum.conf section=main option=proxy value=http://proxy.fx8120.hgdeoro.com.ar:3128
  tags: yum

- name: Use specific YUM mirror
  template: src={{ansible_distribution}}-{{ansible_distribution_version}}--CentOS-Base.repo dest=/etc/yum.repos.d/CentOS-Base.repo
  tags: yum

- name: Install basic packages
  yum: name={{ item }} state=installed
  with_items:
     - vim-enhanced
     - openssh-clients
     - cifs-utils
     - git
     - nfs-utils
     - portmap
#     - tcpdump
#     - nmap
#     - screen
  tags: yum

- name: Setup proxy via env variables
  template: src=etc--profile.d--proxy.sh dest=/etc/profile.d/proxy.sh
  tags: proxy

- name: Setup proxy on wgetrc
  lineinfile: dest=/etc/wgetrc regexp="^{{item.re}}"  line="{{item.line}}"
  with_items:
     - { re: 'http_proxy',  line: 'http_proxy = http://proxy.fx8120.hgdeoro.com.ar:3128' }
     - { re: 'https_proxy', line: 'https_proxy = http://proxy.fx8120.hgdeoro.com.ar:3128' }
     - { re: 'ftp_proxy',   line: 'ftp_proxy = http://proxy.fx8120.hgdeoro.com.ar:3128' }
     - { re: 'use_proxy',   line: 'use_proxy = on' }
  tags: proxy

- name: Create Hadoop group
  group: name=hadoop gid=599 state=present

- name: Create Hadoop user
  user: name=hadoop comment="User for Hadoop services" uid=599 group=hadoop state=present

- name: Setup ssh keys
  authorized_key: user="{{item}}" key="{{lookup('file', 'local/authorized_key.txt' )}}"
  with_items:
     - root
     - horacio
     - hadoop
  tags: ssh

- name: Create directories
  file: path={{item}} owner=hadoop group=hadoop mode=0755 state=directory
  with_items:
     - /srv/nfs
     - /srv/hadoop/hdfs
     - /srv/hadoop/data
     - /srv/hadoop/secondary-namenode-checkpoint
     - /srv/hadoop/mapred/local
     - /srv/hadoop/mapred/system

- name: Setup fstab
  mount: name=/srv/nfs src=nfs.fx8120.hgdeoro.com.ar:/srv/nfs fstype=nfs4 opts=rw state=mounted

- name: Register EPEL repository
  yum: name=http://epel.mirror.mendoza-conicet.gob.ar/6/i386/epel-release-6-8.noarch.rpm state=present

- name: Install Java
  yum: name="{{item}}" state=present
  with_items:
     - http://nfs.fx8120.hgdeoro.com.ar/nfs/ro/jdk/sun-javadb-common-10.6.2-1.1.i386.rpm
     - http://nfs.fx8120.hgdeoro.com.ar/nfs/ro/jdk/sun-javadb-client-10.6.2-1.1.i386.rpm
     - http://nfs.fx8120.hgdeoro.com.ar/nfs/ro/jdk/sun-javadb-core-10.6.2-1.1.i386.rpm
     - http://nfs.fx8120.hgdeoro.com.ar/nfs/ro/jdk/sun-javadb-demo-10.6.2-1.1.i386.rpm
     - http://nfs.fx8120.hgdeoro.com.ar/nfs/ro/jdk/sun-javadb-docs-10.6.2-1.1.i386.rpm
     - http://nfs.fx8120.hgdeoro.com.ar/nfs/ro/jdk/sun-javadb-javadoc-10.6.2-1.1.i386.rpm
     - http://nfs.fx8120.hgdeoro.com.ar/nfs/ro/jdk/jdk-6u31-linux-amd64.rpm
  tags: jdk

- name: Unzip Hadoop
  shell: wget -O - http://nfs.fx8120.hgdeoro.com.ar/nfs/ro/hadoop/hadoop-1.2.0-bin.tar.gz | tar xzf - -C /home/hadoop creates=/home/hadoop/hadoop-1.2.0
  tags: hadoop

- name: Configure Hadoop HDFS
  template: src=hdfs-site.xml dest=/home/hadoop/hadoop-1.2.0/conf/hdfs-site.xml
  tags: hadoop

- name: Configure Hadoop MAPRED
  template: src=mapred-site.xml dest=/home/hadoop/hadoop-1.2.0/conf/mapred-site.xml
  tags: hadoop

- name: Configure Hadoop environment
  lineinfile: dest=/home/hadoop/hadoop-1.2.0/conf/hadoop-env.sh regexp="^{{item.re}}"  line="{{item.line}}"
  with_items:
     - { re: 'export JAVA_HOME=',       line: 'export JAVA_HOME=/usr/java/jdk1.6.0_31' }
     - { re: 'export HADOOP_HEAPSIZE=', line: 'export HADOOP_HEAPSIZE=512' }
     - { re: 'export HADOOP_SSH_OPTS=', line: 'export HADOOP_SSH_OPTS=\"-o ConnectTimeout=5 -o SendEnv=HADOOP_CONF_DIR -o StrictHostKeyChecking=no\"' }
     - { re: 'export HADOOP_LOG_DIR=',  line: 'export HADOOP_LOG_DIR=/srv/nfs/hadoop-1.2.0-logs' }
  tags: hadoop
