---
- name: Check CentOS version
  fail: msg="Only {{ansible_distribution}} {{ansible_distribution_version}} supported"
  when: ansible_distribution != 'CentOS' or ansible_distribution_version != '6.4'
  tags: check

- name: YUM - disable fastestmirror plugin
  ini_file: dest=/etc/yum/pluginconf.d/fastestmirror.conf section=main option=enabled value=0
  tags: yum

- name: YUM - Setup proxy
  ini_file: dest=/etc/yum.conf section=main option=proxy value={{proxy}}
  tags: yum

- name: Use specific YUM mirror
  template: src={{ansible_distribution}}-{{ansible_distribution_version}}--CentOS-Base.repo dest=/etc/yum.repos.d/CentOS-Base.repo
  tags: yum

- name: Install basic packages
  yum: name={{ item }} state=installed
  with_items:
     - vim-enhanced
     - openssh-clients
     - cifs-utils
     - git
     - nfs-utils
     - portmap
#     - tcpdump
#     - nmap
#     - screen
  tags: yum

- name: Setup proxy via env variables
  template: src=etc--profile.d--proxy.sh dest=/etc/profile.d/proxy.sh
  tags: proxy

- name: Setup proxy on wgetrc
  lineinfile: dest=/etc/wgetrc regexp="^{{item.re}}"  line="{{item.line}}"
  with_items:
     - { re: 'http_proxy',  line: 'http_proxy = {{ proxy }}' }
     - { re: 'https_proxy', line: 'https_proxy = {{ proxy }}' }
     - { re: 'ftp_proxy',   line: 'ftp_proxy = {{ proxy }}' }
     - { re: 'use_proxy',   line: 'use_proxy = on' }
  tags: proxy

- name: Create Hadoop group
  group: name=hadoop gid=599 state=present

- name: Create Hadoop user
  user: name=hadoop comment="User for Hadoop services" uid=599 group=hadoop state=present

- name: Setup ssh authorized_key
  authorized_key: user="{{item}}" key="{{lookup('file', 'local/authorized_key.txt' )}}"
  with_items:
     - root
     - horacio
     - hadoop
  tags: ssh

- name: Setup ssh keys
  copy: src=local/{{item.f}} dest={{item.h}}/.ssh/{{item.f}} owner={{item.u}} group={{item.u}} mode=0600
  with_items:
    - { u: 'root',    h: '/root',         f: 'id_rsa' }
    - { u: 'root',    h: '/root',         f: 'id_rsa.pub' }
    - { u: 'hadoop',  h: '/home/hadoop',  f: 'id_rsa' }
    - { u: 'hadoop',  h: '/home/hadoop',  f: 'id_rsa.pub' }
    - { u: 'horacio', h: '/home/horacio', f: 'id_rsa' }
    - { u: 'horacio', h: '/home/horacio', f: 'id_rsa.pub' }
  tags: ssh

- name: Create local directories
  file: path={{item}} owner=hadoop group=hadoop mode=0755 state=directory
  with_items:
     - /srv/nfs
     - /srv/hadoop
     - /srv/hadoop/data
     - /srv/hadoop/secondary-namenode-checkpoint
     - /srv/hadoop/mapred
     - /srv/hadoop/mapred/local
     - /srv/hadoop/mapred/system

- name: Setup fstab
  mount: name=/srv/nfs src={{ nfs_server }}:{{ nfs_export }} fstype=nfs4 opts=rw state=mounted

- name: Create NFS directories
  file: path={{item}} owner=hadoop group=hadoop mode=0775 state=directory
  with_items:
     - /srv/nfs/hadoop-{{hadoop_version}}-logs

- name: Copy RPMs
  copy: src=files/{{item}} dest=/tmp/{{item}} owner=root group=root mode=0644 force=no
  with_items:
     - "sun-javadb-common-10.6.2-1.1.i386.rpm"
     - "sun-javadb-client-10.6.2-1.1.i386.rpm"
     - "sun-javadb-core-10.6.2-1.1.i386.rpm"
     - "sun-javadb-demo-10.6.2-1.1.i386.rpm"
     - "sun-javadb-docs-10.6.2-1.1.i386.rpm"
     - "sun-javadb-javadoc-10.6.2-1.1.i386.rpm"
     - "jdk-6u31-linux-amd64.rpm"
     - "epel-release-6-8.noarch.rpm"
     - "{{ hadoop_tgz }}"
  tags: upload

- name: Register EPEL repository
  yum: name="/tmp/epel-release-6-8.noarch.rpm" state=present
  tags: yum

- name: Install Java
  yum: name="{{item}}" state=present
  with_items:
     - "/tmp/sun-javadb-common-10.6.2-1.1.i386.rpm"
     - "/tmp/sun-javadb-client-10.6.2-1.1.i386.rpm"
     - "/tmp/sun-javadb-core-10.6.2-1.1.i386.rpm"
     - "/tmp/sun-javadb-demo-10.6.2-1.1.i386.rpm"
     - "/tmp/sun-javadb-docs-10.6.2-1.1.i386.rpm"
     - "/tmp/sun-javadb-javadoc-10.6.2-1.1.i386.rpm"
     - "/tmp/jdk-6u31-linux-amd64.rpm"
  tags: jdk

- name: Unzip Hadoop
  command: tar xzf /tmp/{{ hadoop_tgz }} -C /home/hadoop creates=/home/hadoop/{{hadoop_unzip_dir}}
  tags: hadoop

- name: Configure Hadoop
  template: src={{item}} dest=/home/hadoop/{{ hadoop_unzip_dir }}/conf/{{item}}
  with_items:
     - hdfs-site.xml
     - mapred-site.xml
     - core-site.xml
     - masters # this file contains the name or IP of the secondary name node
     - slaves  # this file contains the names or IPs of the slaves nodes
  tags: hadoop

- name: Configure Hadoop environment
  lineinfile: dest=/home/hadoop/{{ hadoop_unzip_dir }}/conf/hadoop-env.sh regexp="^{{item.re}}"  line="{{item.line}}"
  with_items:
     - { re: 'export JAVA_HOME=',       line: 'export JAVA_HOME=/usr/java/jdk1.6.0_31' }
     - { re: 'export HADOOP_HEAPSIZE=', line: 'export HADOOP_HEAPSIZE=512' }
     - { re: 'export HADOOP_SSH_OPTS=', line: 'export HADOOP_SSH_OPTS=\"-o ConnectTimeout=5 -o SendEnv=HADOOP_CONF_DIR -o StrictHostKeyChecking=no\"' }
     - { re: 'export HADOOP_LOG_DIR=',  line: 'export HADOOP_LOG_DIR=/srv/nfs/hadoop-{{hadoop_version}}-logs' }
  tags: hadoop
