---
- name: YUM - disable fastestmirror plugin
  ini_file: dest=/etc/yum/pluginconf.d/fastestmirror.conf section=main option=enabled value=0
  tags: yum

- name: YUM - Setup proxy
  ini_file: dest=/etc/yum.conf section=main option=proxy value=http://proxy.fx8120.hgdeoro.com.ar:3128
  tags: yum

- name: Use specific YUM mirror
  template: src={{ansible_distribution}}-{{ansible_distribution_version}}--CentOS-Base.repo dest=/etc/yum.repos.d/CentOS-Base.repo
  tags: yum

- name: Install basic packages
  yum: name={{ item }} state=installed
  with_items:
     - vim-enhanced
     - openssh-clients
     - cifs-utils
     - git
     - nfs-utils
     - portmap
#     - tcpdump
#     - nmap
#     - screen
  tags: yum

- name: Setup proxy via env variables
  template: src=etc--profile.d--proxy.sh dest=/etc/profile.d/proxy.sh

- name: Setup proxy on wgetrc
  lineinfile: dest=/etc/wgetrc regexp="^{{item.re}}"  line="{{item.line}}"
  with_items:
     - { re: 'http_proxy',  line: 'http_proxy = http://proxy.fx8120.hgdeoro.com.ar:3128' }
     - { re: 'https_proxy', line: 'https_proxy = http://proxy.fx8120.hgdeoro.com.ar:3128' }
     - { re: 'ftp_proxy',   line: 'ftp_proxy = http://proxy.fx8120.hgdeoro.com.ar:3128' }
     - { re: 'use_proxy',   line: 'use_proxy = on' }

- name: Create Hadoop group
  group: name=hadoop gid=599 state=present

- name: Create Hadoop user
  user: name=hadoop comment="User for Hadoop services" uid=599 group=hadoop state=present


- name: Setup ssh keys
  authorized_key: user="{{item}}" key="{{lookup('file', 'local/authorized_key.txt' )}}"
  with_items:
     - root
     - horacio
     - hadoop

